"""empty message

Revision ID: 18f8a70a8d0e
Revises: 
Create Date: 2021-04-18 23:41:07.866136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18f8a70a8d0e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('correct_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correctanswer', sa.Float(), nullable=True),
    sa.Column('n_reg', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('student_id', sa.String(length=64), nullable=True),
    sa.Column('sex', sa.String(length=64), nullable=True),
    sa.Column('age', sa.String(length=64), nullable=True),
    sa.Column('education', sa.String(length=64), nullable=True),
    sa.Column('year', sa.String(length=64), nullable=True),
    sa.Column('area', sa.String(length=120), nullable=True),
    sa.Column('institution', sa.String(length=256), nullable=True),
    sa.Column('experience', sa.String(length=128), nullable=True),
    sa.Column('years_experience', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_age'), 'user', ['age'], unique=False)
    op.create_index(op.f('ix_user_area'), 'user', ['area'], unique=False)
    op.create_index(op.f('ix_user_education'), 'user', ['education'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_experience'), 'user', ['experience'], unique=False)
    op.create_index(op.f('ix_user_institution'), 'user', ['institution'], unique=False)
    op.create_index(op.f('ix_user_sex'), 'user', ['sex'], unique=False)
    op.create_index(op.f('ix_user_student_id'), 'user', ['student_id'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_index(op.f('ix_user_year'), 'user', ['year'], unique=False)
    op.create_index(op.f('ix_user_years_experience'), 'user', ['years_experience'], unique=False)
    op.create_table('submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=120), nullable=True),
    sa.Column('answer', sa.String(length=120), nullable=True),
    sa.Column('correctanswer', sa.Float(), nullable=True),
    sa.Column('verifyanswer', sa.Float(), nullable=True),
    sa.Column('totaltime', sa.String(length=120), nullable=True),
    sa.Column('regulation', sa.String(length=120), nullable=True),
    sa.Column('balance_sheet', sa.String(length=120), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submission')
    op.drop_index(op.f('ix_user_years_experience'), table_name='user')
    op.drop_index(op.f('ix_user_year'), table_name='user')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_student_id'), table_name='user')
    op.drop_index(op.f('ix_user_sex'), table_name='user')
    op.drop_index(op.f('ix_user_institution'), table_name='user')
    op.drop_index(op.f('ix_user_experience'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_education'), table_name='user')
    op.drop_index(op.f('ix_user_area'), table_name='user')
    op.drop_index(op.f('ix_user_age'), table_name='user')
    op.drop_table('user')
    op.drop_table('correct_answer')
    # ### end Alembic commands ###
