"""empty message

Revision ID: 57329cf1b316
Revises: e5f64e667b29
Create Date: 2021-07-10 19:22:25.420502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57329cf1b316'
down_revision = 'e5f64e667b29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('affiliation', sa.String(length=128), nullable=True))
    op.add_column('submission', sa.Column('usertype', sa.String(length=120), nullable=True))
    op.drop_column('submission', 'username')
    op.add_column('user', sa.Column('affiliation', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('businessemail', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_user_affiliation'), 'user', ['affiliation'], unique=True)
    op.create_index(op.f('ix_user_businessemail'), 'user', ['businessemail'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_businessemail'), table_name='user')
    op.drop_index(op.f('ix_user_affiliation'), table_name='user')
    op.drop_column('user', 'businessemail')
    op.drop_column('user', 'affiliation')
    op.add_column('submission', sa.Column('username', sa.VARCHAR(length=120), nullable=True))
    op.drop_column('submission', 'usertype')
    op.drop_column('submission', 'affiliation')
    # ### end Alembic commands ###
