"""empty message

Revision ID: 644a3169e3b9
Revises: e0a8153d4c28
Create Date: 2021-04-18 12:33:27.992433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '644a3169e3b9'
down_revision = 'e0a8153d4c28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('totaltime', sa.String(length=120), nullable=True))
    op.drop_column('submission', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    op.drop_column('submission', 'totaltime')
    # ### end Alembic commands ###
