"""empty message

Revision ID: 81115680b347
Revises: e790a6127aec
Create Date: 2021-04-18 12:22:18.963165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81115680b347'
down_revision = 'e790a6127aec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_submission_timestamp', table_name='submission')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_submission_timestamp', 'submission', ['timestamp'], unique=False)
    # ### end Alembic commands ###
