"""empty message

Revision ID: cc8f2adb2969
Revises: 18f8a70a8d0e
Create Date: 2021-04-19 13:12:49.126536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc8f2adb2969'
down_revision = '18f8a70a8d0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('username', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'username')
    # ### end Alembic commands ###
