"""empty message

Revision ID: e5f64e667b29
Revises: cc8f2adb2969
Create Date: 2021-04-19 13:18:10.851332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5f64e667b29'
down_revision = 'cc8f2adb2969'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    None
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    None
    # ### end Alembic commands ###
